
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

import Navbar from "@/Components/Header/Navbar";
import {color} from "framer-motion";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "RWADY",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html  >
      <head>
          <title>RWADY</title>
          <link rel="stylesheet"
                href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"/>
          <style>
          .mainContainer{

          }
          </style>
      </head>

      <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased rtl`}


      >
      {/*<div className={"mainContainer"}>*/}
          {children}
      {/*</div>*/}
      </body>
      </html>
  );
}
